# Generated by Django 5.0.4 on 2024-04-12 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asignatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=6, verbose_name='Codigo de asignatura')),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre de asignatura')),
                ('uv', models.IntegerField(verbose_name='Unidades valorativas')),
            ],
            options={
                'verbose_name': 'Asignatura',
                'verbose_name_plural': 'Asignaturas',
            },
        ),
    ]
